export enum ItemID {

	// #region | 0+: Natural Resources
	COAL = 0,
	COPPER_ORE = 1,
	DIRT = 2,
	GOLD_ORE = 3,
	IRON_ORE = 4,
	LIMESTONE = 5,
	QUARTZ = 6,
	ROCK = 7,
	SAND = 8,
	SEAWATER = 9,
	SULFUR = 10,
	URANIUM_ORE = 11,
	WOOD = 12,
	WATER = 13,
	// #endregion

	// #region | 100+: Semi-Processed Resources
	ACID = 100,
	BRINE = 101,
	BROKEN_GLASS = 102,
	CEMENT = 103,
	CHILLED_WATER = 104,
	COPPER_ORE_CRUSHED = 105,
	COPPER_SCRAP = 106,
	COPPER_SCRAP_PRESSED = 107,
	GLASS_MIX = 108,
	GOLD_ORE_CONCENTRATE = 109,
	GOLD_ORE_CRUSHED = 110,
	GOLD_ORE_POWDER = 111,
	GOLD_SCRAP = 112,
	GOLD_SCRAP_PRESSED = 113,
	GRAPHITE = 114,
	GRAVEL = 115,
	IMPURE_COPPER = 116,
	IRON_ORE_CRUSHED = 117,
	IRON_SCRAP = 118,
	IRON_SCRAP_PRESSED = 119,
	MANUFACTURED_SAND = 120,
	MOLTEN_COPPER = 121,
	MOLTEN_GLASS = 122,
	MOLTEN_IRON = 123,
	MOLTEN_SILICON = 124,
	MOLTEN_STEEL = 125,
	QUARTZ_CRUSHED = 126,
	RECYCLABLES = 127,
	RECYCLABLES_PRESSED = 128,
	SALT = 129,
	SLAG_CRUSHED = 130,
	URANIUM_ORE_CRUSHED = 131,
	WOODCHIPS = 132,
	// #endregion

	// #region | 200+: Crafted Materials
	BRICKS = 200,
	CONCRETE_SLAB = 201,
	CONSTRUCTION_PARTS = 202,
	CONSTRUCTION_PARTS_II = 203,
	CONSTRUCTION_PARTS_III = 204,
	CONSTRUCTION_PARTS_IV = 205,
	CONSUMER_ELECTRONICS = 206,
	COPPER = 207,
	ELECTRONICS = 208,
	ELECTRONICS_II = 209,
	ELECTRONICS_III = 210,
	FILTER_MEDIA = 211,
	FLOWERS = 212,
	GLASS = 213,
	GOLD = 214,
	HOUSEHOLD_APPLIANCES = 215,
	HOUSEHOLD_GOODS = 216,
	IRON = 217,
	LAB_EQUIPMENT = 218,
	LAB_EQUIPMENT_II = 219,
	LAB_EQUIPMENT_III = 220,
	LAB_EQUIPMENT_IV = 221,
	MAINTENANCE_I = 222,
	MAINTENANCE_II = 223,
	MAINTENANCE_III = 224,
	MECHANICAL_PARTS = 225,
	MICROCHIPS = 226,
	MICROCHIPS_STAGE_1_A = 227,
	MICROCHIPS_STAGE_1_B = 228,
	MICROCHIPS_STAGE_1_C = 229,
	MICROCHIPS_STAGE_2_A = 230,
	MICROCHIPS_STAGE_2_B = 231,
	MICROCHIPS_STAGE_2_C = 232,
	MICROCHIPS_STAGE_3_A = 233,
	MICROCHIPS_STAGE_3_B = 234,
	MICROCHIPS_STAGE_3_C = 235,
	MICROCHIPS_STAGE_4_A = 236,
	MICROCHIPS_STAGE_4_B = 237,
	PAPER = 238,
	PCB = 239,
	SERVER = 240,
	SILICON_POLY = 241,
	SILICON_WAFER = 242,
	SOLAR_CELL = 243,
	SOLAR_CELL_MONO = 244,
	STEEL = 245,
	VEHICLE_PARTS = 246,
	VEHICLE_PARTS_II = 247,
	VEHICLE_PARTS_III = 248,
	// #endregion

	// #region | 300+: Foods and Medicals
	ANESTHETICS = 300,
	ANIMAL_FEED = 301,
	ANTIBIOTICS = 302,
	BREAD = 303,
	CAKE = 304,
	CANOLA = 305,
	CHICKEN_CARCASS = 306,
	COMPOST = 307,
	COOKING_OIL = 308,
	CORN_MASH = 309,
	CORN = 310,
	DISINFECTANT = 311,
	EGGS = 312,
	ETHANOL = 313,
	FERTILITY = 314,
	FERTILIZER_ORGANIC = 315,
	FERTILIZER_I = 316,
	FERTILIZER_II = 317,
	FLOUR = 318,
	FOOD_PACK = 319,
	FRUIT = 320,
	GREEN_MANURE = 321,
	MEAT_TRIMMINGS = 322,
	MEAT = 323,
	MEDICAL_EQUIPMENT = 324,
	MEDICAL_SUPPLIES = 325,
	MEDICAL_SUPPLIES_II = 326,
	MEDICAL_SUPPLIES_III = 327,
	MORPHINE = 328,
	POPPY = 329,
	POTATO = 330,
	SAUSAGE = 331,
	SNACK = 332,
	SOYBEAN = 333,
	SUGAR_CANE = 334,
	SUGAR = 335,
	TOFU = 336,
	TREE_SAPLING = 337,
	VEGETABLES = 338,
	WHEAT = 339,
	// #endregion

	// #region | 400+: Petrochemicals
	CRUDE_OIL = 400,
	SOUR_WATER = 401,
	HEAVY_OIL = 402,
	MEDIUM_OIL = 403,
	DIESEL = 404,
	LIGHT_OIL = 405,
	FUEL_GAS = 406,
	NAPHTHA = 407,
	AMMONIA = 408,
	CHLORINE = 409,
	HYDROGEN = 410,
	NITROGEN = 411,
	OXYGEN = 412,
	HYDROGEN_FLUORIDE = 413,
	PLASTIC = 414,
	RUBBER = 415,
	// #endregion

	// #region | 500+: Power and Nuclears
	ELECTRICITY = 500,
	MECHANICAL_POWER = 501,
	HEAT = 502,
	STEAM_SUPER = 503,
	STEAM_HIGH = 504,
	STEAM_LOW = 505,
	STEAM_DEPLETED = 506,
	BLANKET_FUEL = 507,
	BLANKET_FUEL_ENRICHED = 508,
	CORE_FUEL = 509,
	CORE_FUEL_SPENT = 510,
	DEPLETED_URANIUM = 511,
	ENRICHED_URANIUM_4 = 512,
	ENRICHED_URANIUM_20 = 513,
	FISSION_PRODUCT = 514,
	MOX_ROD = 515,
	PLUTONIUM = 516,
	REPROCESSED_URANIUM_1 = 517,
	RETIRED_WASTE = 518,
	SPENT_FUEL = 519,
	SPENT_MOX = 520,
	URANIUM_ROD = 521,
	YELLOW_CAKE = 522,
	// #endregion

	// #region | 600+: Wastes and Pollution
	AIR_POLLUTION = 600,
	BIOMASS = 601,
	CARBON_DIOXIDE = 602,
	EXHAUST = 603,
	RADIATION = 604,
	SLAG = 605,
	SLUDGE = 606,
	TOXIC_SLURRY = 607,
	WASTE = 608,
	WATER_POLLUTION = 609,
	WASTE_PRESSED = 610,
	WASTE_WATER = 611
	// #endregion
}

enum ItemCategory {
	NATURAL_RESOURCE = 0,
	SEMI_PROCESSED_RESOURCE = 1,
	CRAFTED_MATERIAL = 2,
	FOOD_AND_MEDICAL = 3,
	PETROCHEMICAL = 4,
	POWER_AND_NUCLEAR = 5,
	WASTE_AND_POLLUTION = 6
}

enum ItemState {
	LOOSE = 0,
	UNIT = 1,
	FLUID = 2,
	MOLTEN = 3,
	MECHANICAL = 4,
	VIRTUAL = 5
}

export type ItemCount = Partial<{
	[key in ItemID]: number
}>;

class Item {
	public readonly name: string;
	private readonly category: ItemCategory;
	private readonly state: ItemState;

	constructor(
		name: string,
		category: ItemCategory,
		state: ItemState
	) {
		this.name = name;
		this.category = category;
		this.state = state;
	}
}

const items: Record<ItemID, Item> = {

	// #region | Natural Resources
	[ItemID.COAL]: new Item("Coal", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.COPPER_ORE]: new Item("Copper Ore", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.DIRT]: new Item("Dirt", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.GOLD_ORE]: new Item("Gold Ore", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.IRON_ORE]: new Item("Iron Ore", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.LIMESTONE]: new Item("Limestone", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.QUARTZ]: new Item("Quartz", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.ROCK]: new Item("Rock", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.SAND]: new Item("Sand", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.SEAWATER]: new Item("Seawater", ItemCategory.NATURAL_RESOURCE, ItemState.FLUID),
	[ItemID.SULFUR]: new Item("Sulfur", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.URANIUM_ORE]: new Item("Uranium Ore", ItemCategory.NATURAL_RESOURCE, ItemState.LOOSE),
	[ItemID.WOOD]: new Item("Wood", ItemCategory.NATURAL_RESOURCE, ItemState.UNIT),
	[ItemID.WATER]: new Item("Water", ItemCategory.NATURAL_RESOURCE, ItemState.FLUID),
	// #endregion

	// #region | Semi-Processed Resources
	[ItemID.ACID]: new Item("Acid", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.FLUID),
	[ItemID.BRINE]: new Item("Brine", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.FLUID),
	[ItemID.BROKEN_GLASS]: new Item("Broken Glass", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.CEMENT]: new Item("Cement", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.UNIT),
	[ItemID.CHILLED_WATER]: new Item("Chilled Water", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.FLUID),
	[ItemID.COPPER_ORE_CRUSHED]: new Item("Copper Ore Crushed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.COPPER_SCRAP]: new Item("Copper Scrap", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.COPPER_SCRAP_PRESSED]: new Item("Copper Scrap Pressed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GLASS_MIX]: new Item("Glass Mix", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GOLD_ORE_CONCENTRATE]: new Item("Gold Ore Concentrate", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GOLD_ORE_CRUSHED]: new Item("Gold Ore Crushed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GOLD_ORE_POWDER]: new Item("Gold Ore Powder", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GOLD_SCRAP]: new Item("Gold Scrap", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GOLD_SCRAP_PRESSED]: new Item("Gold Scrap Pressed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.GRAPHITE]: new Item("Graphite", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.UNIT),
	[ItemID.GRAVEL]: new Item("Gravel", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.IMPURE_COPPER]: new Item("Impure Copper", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.UNIT),
	[ItemID.IRON_ORE_CRUSHED]: new Item("Iron Ore Crushed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.IRON_SCRAP]: new Item("Iron Scrap", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.IRON_SCRAP_PRESSED]: new Item("Iron Scrap Pressed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.MANUFACTURED_SAND]: new Item("Manufactured Sand", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.MOLTEN_COPPER]: new Item("Molten Copper", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.MOLTEN),
	[ItemID.MOLTEN_GLASS]: new Item("Molten Glass", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.MOLTEN),
	[ItemID.MOLTEN_IRON]: new Item("Molten Iron", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.MOLTEN),
	[ItemID.MOLTEN_SILICON]: new Item("Molten Silicon", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.MOLTEN),
	[ItemID.MOLTEN_STEEL]: new Item("Molten Steel", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.MOLTEN),
	[ItemID.QUARTZ_CRUSHED]: new Item("Quartz Crushed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.RECYCLABLES]: new Item("Recyclables", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.RECYCLABLES_PRESSED]: new Item("Recyclables Pressed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.SALT]: new Item("Salt", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.SLAG_CRUSHED]: new Item("Slag Crushed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.URANIUM_ORE_CRUSHED]: new Item("Uranium Ore Crushed", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	[ItemID.WOODCHIPS]: new Item("Woodchips", ItemCategory.SEMI_PROCESSED_RESOURCE, ItemState.LOOSE),
	// #endregion

	// #region | Crafted Materials
	[ItemID.BRICKS]: new Item("Bricks", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.CONCRETE_SLAB]: new Item("Concrete Slab", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.CONSTRUCTION_PARTS]: new Item("Construction Parts", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.CONSTRUCTION_PARTS_II]: new Item("Construction Parts II", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.CONSTRUCTION_PARTS_III]: new Item("Construction Parts III", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.CONSTRUCTION_PARTS_IV]: new Item("Construction Parts IV", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.CONSUMER_ELECTRONICS]: new Item("Consumer Electronics", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.COPPER]: new Item("Copper", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.ELECTRONICS]: new Item("Electronics", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.ELECTRONICS_II]: new Item("Electronics II", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.ELECTRONICS_III]: new Item("Electronics III", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.FILTER_MEDIA]: new Item("Filter Media", ItemCategory.CRAFTED_MATERIAL, ItemState.LOOSE),
	[ItemID.FLOWERS]: new Item("Flowers", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.GLASS]: new Item("Glass", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.GOLD]: new Item("Gold", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.HOUSEHOLD_APPLIANCES]: new Item("Household Appliances", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.HOUSEHOLD_GOODS]: new Item("Household Goods", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.IRON]: new Item("Iron", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.LAB_EQUIPMENT]: new Item("Lab Equipment", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.LAB_EQUIPMENT_II]: new Item("Lab Equipment II", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.LAB_EQUIPMENT_III]: new Item("Lab Equipment III", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.LAB_EQUIPMENT_IV]: new Item("Lab Equipment IV", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MAINTENANCE_I]: new Item("Maintenance I", ItemCategory.CRAFTED_MATERIAL, ItemState.VIRTUAL),
	[ItemID.MAINTENANCE_II]: new Item("Maintenance II", ItemCategory.CRAFTED_MATERIAL, ItemState.VIRTUAL),
	[ItemID.MAINTENANCE_III]: new Item("Maintenance III", ItemCategory.CRAFTED_MATERIAL, ItemState.VIRTUAL),
	[ItemID.MECHANICAL_PARTS]: new Item("Mechanical Parts", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS]: new Item("Microchips", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_1_A]: new Item("Microchips Stage 1 A", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_1_B]: new Item("Microchips Stage 1 B", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_1_C]: new Item("Microchips Stage 1 C", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_2_A]: new Item("Microchips Stage 2 A", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_2_B]: new Item("Microchips Stage 2 B", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_2_C]: new Item("Microchips Stage 2 C", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_3_A]: new Item("Microchips Stage 3 A", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_3_B]: new Item("Microchips Stage 3 B", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_3_C]: new Item("Microchips Stage 3 C", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_4_A]: new Item("Microchips Stage 4 A", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.MICROCHIPS_STAGE_4_B]: new Item("Microchips Stage 4 B", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.PAPER]: new Item("Paper", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.PCB]: new Item("PCB", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.SERVER]: new Item("Server", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.SILICON_POLY]: new Item("Silicon (Poly)", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.SILICON_WAFER]: new Item("Silicon Wafer", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.SOLAR_CELL]: new Item("Solar Cell", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.SOLAR_CELL_MONO]: new Item("Solar Cell Mono", ItemCategory.CRAFTED_MATERIAL, ItemState.LOOSE),
	[ItemID.STEEL]: new Item("Steel", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.VEHICLE_PARTS]: new Item("Vehicle Parts", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.VEHICLE_PARTS_II]: new Item("Vehicle Parts II", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	[ItemID.VEHICLE_PARTS_III]: new Item("Vehicle Parts III", ItemCategory.CRAFTED_MATERIAL, ItemState.UNIT),
	// #endregion

	// #region | Foods and Medicals
	[ItemID.ANESTHETICS]: new Item("Anesthetics", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.ANIMAL_FEED]: new Item("Animal Feed", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.ANTIBIOTICS]: new Item("Antibiotics", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.BREAD]: new Item("Bread", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.CAKE]: new Item("Cake", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.CANOLA]: new Item("Canola", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.CHICKEN_CARCASS]: new Item("Chicken Carcass", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.COMPOST]: new Item("Compost", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.COOKING_OIL]: new Item("Cooking Oil", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.CORN_MASH]: new Item("Corn Mash", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.CORN]: new Item("Corn", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.DISINFECTANT]: new Item("Disinfectant", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.EGGS]: new Item("Eggs", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.ETHANOL]: new Item("Ethanol", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.FERTILITY]: new Item("Fertility", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.FERTILIZER_ORGANIC]: new Item("Fertilizer (Organic)", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.FERTILIZER_I]: new Item("Fertilizer I", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.FERTILIZER_II]: new Item("Fertilizer II", ItemCategory.FOOD_AND_MEDICAL, ItemState.FLUID),
	[ItemID.FLOUR]: new Item("Flour", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.FOOD_PACK]: new Item("Food Pack", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.FRUIT]: new Item("Fruit", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.GREEN_MANURE]: new Item("Green Manure", ItemCategory.FOOD_AND_MEDICAL, ItemState.VIRTUAL),
	[ItemID.MEAT_TRIMMINGS]: new Item("Meat Trimmings", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.MEAT]: new Item("Meat", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.MEDICAL_EQUIPMENT]: new Item("Medical Equipment", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.MEDICAL_SUPPLIES]: new Item("Medical Supplies", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.MEDICAL_SUPPLIES_II]: new Item("Medical Supplies II", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.MEDICAL_SUPPLIES_III]: new Item("Medical Supplies III", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.MORPHINE]: new Item("Morphine", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.POPPY]: new Item("Poppy", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.POTATO]: new Item("Potato", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.SAUSAGE]: new Item("Sausage", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.SNACK]: new Item("Snack", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.SOYBEAN]: new Item("Soybean", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.SUGAR_CANE]: new Item("Sugar Cane", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.SUGAR]: new Item("Sugar", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	[ItemID.TOFU]: new Item("Tofu", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.TREE_SAPLING]: new Item("Tree Sapling", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.VEGETABLES]: new Item("Vegetables", ItemCategory.FOOD_AND_MEDICAL, ItemState.UNIT),
	[ItemID.WHEAT]: new Item("Wheat", ItemCategory.FOOD_AND_MEDICAL, ItemState.LOOSE),
	// #endregion

	// #region | Petrochemicals
	[ItemID.CRUDE_OIL]: new Item("Crude Oil", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.SOUR_WATER]: new Item("Sour Water", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.HEAVY_OIL]: new Item("Heavy Oil", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.MEDIUM_OIL]: new Item("Medium Oil", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.DIESEL]: new Item("Diesel", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.LIGHT_OIL]: new Item("Light Oil", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.FUEL_GAS]: new Item("Fuel Gas", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.NAPHTHA]: new Item("Naphtha", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.AMMONIA]: new Item("Ammonia", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.CHLORINE]: new Item("Chlorine", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.HYDROGEN]: new Item("Hydrogen", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.NITROGEN]: new Item("Nitrogen", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.OXYGEN]: new Item("Oxygen", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.HYDROGEN_FLUORIDE]: new Item("Hydrogen Fluoride", ItemCategory.PETROCHEMICAL, ItemState.FLUID),
	[ItemID.PLASTIC]: new Item("Plastic", ItemCategory.PETROCHEMICAL, ItemState.UNIT),
	[ItemID.RUBBER]: new Item("Rubber", ItemCategory.PETROCHEMICAL, ItemState.UNIT),
	// #endregion

	// #region | Power and Nuclears
	[ItemID.ELECTRICITY]: new Item("Electricity", ItemCategory.POWER_AND_NUCLEAR, ItemState.VIRTUAL),
	[ItemID.MECHANICAL_POWER]: new Item("Mechanical Power", ItemCategory.POWER_AND_NUCLEAR, ItemState.MECHANICAL),
	[ItemID.HEAT]: new Item("Heat", ItemCategory.POWER_AND_NUCLEAR, ItemState.VIRTUAL),
	[ItemID.STEAM_SUPER]: new Item("Steam (Super)", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.STEAM_HIGH]: new Item("Steam (High)", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.STEAM_LOW]: new Item("Steam (Low)", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.STEAM_DEPLETED]: new Item("Steam Depleted", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.BLANKET_FUEL]: new Item("Blanket Fuel", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.BLANKET_FUEL_ENRICHED]: new Item("Blanket Fuel (Enriched)", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.CORE_FUEL]: new Item("Core Fuel", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.CORE_FUEL_SPENT]: new Item("Core Fuel (Spent)", ItemCategory.POWER_AND_NUCLEAR, ItemState.FLUID),
	[ItemID.DEPLETED_URANIUM]: new Item("Depleted Uranium", ItemCategory.POWER_AND_NUCLEAR, ItemState.LOOSE),
	[ItemID.ENRICHED_URANIUM_4]: new Item("Enriched Uranium (4%)", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.ENRICHED_URANIUM_20]: new Item("Enriched Uranium (20%)", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.FISSION_PRODUCT]: new Item("Fission Product", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.MOX_ROD]: new Item("MOX Rod", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.PLUTONIUM]: new Item("Plutonium", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.REPROCESSED_URANIUM_1]: new Item("Reprocessed Uranium (1%)", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.RETIRED_WASTE]: new Item("Retired Waste", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.SPENT_FUEL]: new Item("Spent Fuel", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.SPENT_MOX]: new Item("Spent MOX", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.URANIUM_ROD]: new Item("Uranium Rod", ItemCategory.POWER_AND_NUCLEAR, ItemState.UNIT),
	[ItemID.YELLOW_CAKE]: new Item("Yellow Cake", ItemCategory.POWER_AND_NUCLEAR, ItemState.LOOSE),
	// #endregion

	// #region | Wastes and Pollution
	[ItemID.AIR_POLLUTION]: new Item("Air Pollution", ItemCategory.WASTE_AND_POLLUTION, ItemState.VIRTUAL),
	[ItemID.BIOMASS]: new Item("Biomass", ItemCategory.WASTE_AND_POLLUTION, ItemState.LOOSE),
	[ItemID.CARBON_DIOXIDE]: new Item("Carbon Dioxide", ItemCategory.WASTE_AND_POLLUTION, ItemState.FLUID),
	[ItemID.EXHAUST]: new Item("Exhaust", ItemCategory.WASTE_AND_POLLUTION, ItemState.FLUID),
	[ItemID.RADIATION]: new Item("Radiation", ItemCategory.WASTE_AND_POLLUTION, ItemState.VIRTUAL),
	[ItemID.SLAG]: new Item("Slag", ItemCategory.WASTE_AND_POLLUTION, ItemState.LOOSE),
	[ItemID.SLUDGE]: new Item("Sludge", ItemCategory.WASTE_AND_POLLUTION, ItemState.LOOSE),
	[ItemID.TOXIC_SLURRY]: new Item("Toxic Slurry", ItemCategory.WASTE_AND_POLLUTION, ItemState.FLUID),
	[ItemID.WASTE]: new Item("Waste", ItemCategory.WASTE_AND_POLLUTION, ItemState.LOOSE),
	[ItemID.WATER_POLLUTION]: new Item("Water Pollution", ItemCategory.WASTE_AND_POLLUTION, ItemState.VIRTUAL),
	[ItemID.WASTE_PRESSED]: new Item("Waste Pressed", ItemCategory.WASTE_AND_POLLUTION, ItemState.LOOSE),
	[ItemID.WASTE_WATER]: new Item("Waste Water",ItemCategory.WASTE_AND_POLLUTION, ItemState.FLUID),
	// #endregion
};
