// Unique numeric item IDs
export enum ItemID {

	// #region | 0+: Natural Resources
	COAL = 0,
	COPPER_ORE = 1,
	DIRT = 2,
	GOLD_ORE = 3,
	IRON_ORE = 4,
	LIMESTONE = 5,
	QUARTZ = 6,
	ROCK = 7,
	SAND = 8,
	SEAWATER = 9,
	SULFUR = 10,
	URANIUM_ORE = 11,
	WOOD = 12,
	WATER = 13,
	// #endregion

	// #region | 100+: Semi-Processed Resources
	ACID = 100,
	BRINE = 101,
	BROKEN_GLASS = 102,
	CEMENT = 103,
	CHILLED_WATER = 104,
	COPPER_ORE_CRUSHED = 105,
	COPPER_SCRAP = 106,
	COPPER_SCRAP_PRESSED = 107,
	GLASS_MIX = 108,
	GOLD_ORE_CONCENTRATE = 109,
	GOLD_ORE_CRUSHED = 110,
	GOLD_ORE_POWDER = 111,
	GOLD_SCRAP = 112,
	GOLD_SCRAP_PRESSED = 113,
	GRAPHITE = 114,
	GRAVEL = 115,
	IMPURE_COPPER = 116,
	IRON_ORE_CRUSHED = 117,
	IRON_SCRAP = 118,
	IRON_SCRAP_PRESSED = 119,
	MANUFACTURED_SAND = 120,
	MOLTEN_COPPER = 121,
	MOLTEN_GLASS = 122,
	MOLTEN_IRON = 123,
	MOLTEN_SILICON = 124,
	MOLTEN_STEEL = 125,
	QUARTZ_CRUSHED = 126,
	RECYCLABLES = 127,
	RECYCLABLES_PRESSED = 128,
	SALT = 129,
	SLAG_CRUSHED = 130,
	URANIUM_ORE_CRUSHED = 131,
	WOODCHIPS = 132,
	// #endregion

	// #region | 200+: Crafted Materials
	BRICKS = 200,
	CONCRETE_SLAB = 201,
	CONSTRUCTION_PARTS = 202,
	CONSTRUCTION_PARTS_II = 203,
	CONSTRUCTION_PARTS_III = 204,
	CONSTRUCTION_PARTS_IV = 205,
	CONSUMER_ELECTRONICS = 206,
	COPPER = 207,
	ELECTRONICS = 208,
	ELECTRONICS_II = 209,
	ELECTRONICS_III = 210,
	FILTER_MEDIA = 211,
	FLOWERS = 212,
	GLASS = 213,
	GOLD = 214,
	HOUSEHOLD_APPLIANCES = 215,
	HOUSEHOLD_GOODS = 216,
	IRON = 217,
	LAB_EQUIPMENT = 218,
	LAB_EQUIPMENT_II = 219,
	LAB_EQUIPMENT_III = 220,
	LAB_EQUIPMENT_IV = 221,
	MAINTENANCE_I = 222,
	MAINTENANCE_II = 223,
	MAINTENANCE_III = 224,
	MECHANICAL_PARTS = 225,
	MICROCHIPS = 226,
	MICROCHIPS_STAGE_1_A = 227,
	MICROCHIPS_STAGE_1_B = 228,
	MICROCHIPS_STAGE_1_C = 229,
	MICROCHIPS_STAGE_2_A = 230,
	MICROCHIPS_STAGE_2_B = 231,
	MICROCHIPS_STAGE_2_C = 232,
	MICROCHIPS_STAGE_3_A = 233,
	MICROCHIPS_STAGE_3_B = 234,
	MICROCHIPS_STAGE_3_C = 235,
	MICROCHIPS_STAGE_4_A = 236,
	MICROCHIPS_STAGE_4_B = 237,
	PAPER = 238,
	PCB = 239,
	SERVER = 240,
	SILICON_POLY = 241,
	SILICON_WAFER = 242,
	SOLAR_CELL = 243,
	SOLAR_CELL_MONO = 244,
	STEEL = 245,
	VEHICLE_PARTS = 246,
	VEHICLE_PARTS_II = 247,
	VEHICLE_PARTS_III = 248,
	// #endregion

	// #region | 300+: Foods and Medicals
	ANESTHETICS = 300,
	ANIMAL_FEED = 301,
	ANTIBIOTICS = 302,
	BREAD = 303,
	CAKE = 304,
	CANOLA = 305,
	CHICKEN_CARCASS = 306,
	COMPOST = 307,
	COOKING_OIL = 308,
	CORN_MASH = 309,
	CORN = 310,
	DISINFECTANT = 311,
	EGGS = 312,
	ETHANOL = 313,
	FERTILITY = 314,
	FERTILIZER_ORGANIC = 315,
	FERTILIZER_I = 316,
	FERTILIZER_II = 317,
	FLOUR = 318,
	FOOD_PACK = 319,
	FRUIT = 320,
	GREEN_MANURE = 321,
	MEAT_TRIMMINGS = 322,
	MEAT = 323,
	MEDICAL_EQUIPMENT = 324,
	MEDICAL_SUPPLIES = 325,
	MEDICAL_SUPPLIES_II = 326,
	MEDICAL_SUPPLIES_III = 327,
	MORPHINE = 328,
	POPPY = 329,
	POTATO = 330,
	SAUSAGE = 331,
	SNACK = 332,
	SOYBEAN = 333,
	SUGAR_CANE = 334,
	SUGAR = 335,
	TOFU = 336,
	TREE_SAPLING = 337,
	VEGETABLES = 338,
	WHEAT = 339,
	// #endregion

	// #region | 400+: Petrochemicals
	CRUDE_OIL = 400,
	SOUR_WATER = 401,
	HEAVY_OIL = 402,
	MEDIUM_OIL = 403,
	DIESEL = 404,
	LIGHT_OIL = 405,
	FUEL_GAS = 406,
	NAPHTHA = 407,
	AMMONIA = 408,
	CHLORINE = 409,
	HYDROGEN = 410,
	NITROGEN = 411,
	OXYGEN = 412,
	HYDROGEN_FLUORIDE = 413,
	PLASTIC = 414,
	RUBBER = 415,
	// #endregion

	// #region | 500+: Power and Nuclears
	ELECTRICITY = 500,
	MECHANICAL_POWER = 501,
	HEAT = 502,
	STEAM_SUPER = 503,
	STEAM_HIGH = 504,
	STEAM_LOW = 505,
	STEAM_DEPLETED = 506,
	BLANKET_FUEL = 507,
	BLANKET_FUEL_ENRICHED = 508,
	CORE_FUEL = 509,
	CORE_FUEL_SPENT = 510,
	DEPLETED_URANIUM = 511,
	ENRICHED_URANIUM_4 = 512,
	ENRICHED_URANIUM_20 = 513,
	FISSION_PRODUCT = 514,
	MOX_ROD = 515,
	PLUTONIUM = 516,
	REPROCESSED_URANIUM_1 = 517,
	RETIRED_WASTE = 518,
	SPENT_FUEL = 519,
	SPENT_MOX = 520,
	URANIUM_ROD = 521,
	YELLOW_CAKE = 522,
	// #endregion

	// #region | 600+: Wastes and Pollution
	AIR_POLLUTION = 600,
	BIOMASS = 601,
	CARBON_DIOXIDE = 602,
	EXHAUST = 603,
	RADIATION = 604,
	SLAG = 605,
	SLUDGE = 606,
	TOXIC_SLURRY = 607,
	WASTE = 608,
	WATER_POLLUTION = 609,
	WASTE_PRESSED = 610,
	WASTE_WATER = 611
	// #endregion
}

// Item categories
enum ItemCategory {
	NATURAL_RESOURCE = 0,
	SEMI_PROCESSED_RESOURCE = 1,
	CRAFTED_MATERIAL = 2,
	FOOD_AND_MEDICAL = 3,
	PETROCHEMICAL = 4,
	POWER_AND_NUCLEAR = 5,
	WASTE_AND_POLLUTION = 6
}

// Item states
enum ItemState {
	LOOSE = 0,
	UNIT = 1,
	FLUID = 2,
	MOLTEN = 3,
	MECHANICAL = 4,
	VIRTUAL = 5
}

// Item count type
export type ItemCount = Partial<Record<ItemID, number>>;

// Structure of item data
interface ItemData {
	name: string,
	category: ItemCategory,
	state: ItemState
}

// All item data
const item_data: Record<ItemID, ItemData> = {

	// #region | Natural Resources
	[ItemID.COAL]: { name: "Coal", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.COPPER_ORE]: { name: "Copper Ore", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.DIRT]: { name: "Dirt", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GOLD_ORE]: { name: "Gold Ore", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.IRON_ORE]: { name: "Iron Ore", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.LIMESTONE]: { name: "Limestone", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.QUARTZ]: { name: "Quartz", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.ROCK]: { name: "Rock", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.SAND]: { name: "Sand", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.SEAWATER]: { name: "Seawater", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.FLUID},
	[ItemID.SULFUR]: { name: "Sulfur", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.URANIUM_ORE]: { name: "Uranium Ore", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.LOOSE},
	[ItemID.WOOD]: { name: "Wood", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.UNIT},
	[ItemID.WATER]: { name: "Water", category: ItemCategory.NATURAL_RESOURCE, state: ItemState.FLUID},
	// #endregion

	// #region | Semi-Processed Resources
	[ItemID.ACID]: { name: "Acid", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.FLUID},
	[ItemID.BRINE]: { name: "Brine", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.FLUID},
	[ItemID.BROKEN_GLASS]: { name: "Broken Glass", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.CEMENT]: { name: "Cement", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.UNIT},
	[ItemID.CHILLED_WATER]: { name: "Chilled Water", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.FLUID},
	[ItemID.COPPER_ORE_CRUSHED]: { name: "Copper Ore Crushed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.COPPER_SCRAP]: { name: "Copper Scrap", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.COPPER_SCRAP_PRESSED]: { name: "Copper Scrap Pressed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GLASS_MIX]: { name: "Glass Mix", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GOLD_ORE_CONCENTRATE]: { name: "Gold Ore Concentrate", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GOLD_ORE_CRUSHED]: { name: "Gold Ore Crushed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GOLD_ORE_POWDER]: { name: "Gold Ore Powder", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GOLD_SCRAP]: { name: "Gold Scrap", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GOLD_SCRAP_PRESSED]: { name: "Gold Scrap Pressed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.GRAPHITE]: { name: "Graphite", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.UNIT},
	[ItemID.GRAVEL]: { name: "Gravel", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.IMPURE_COPPER]: { name: "Impure Copper", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.UNIT},
	[ItemID.IRON_ORE_CRUSHED]: { name: "Iron Ore Crushed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.IRON_SCRAP]: { name: "Iron Scrap", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.IRON_SCRAP_PRESSED]: { name: "Iron Scrap Pressed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.MANUFACTURED_SAND]: { name: "Manufactured Sand", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.MOLTEN_COPPER]: { name: "Molten Copper", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.MOLTEN},
	[ItemID.MOLTEN_GLASS]: { name: "Molten Glass", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.MOLTEN},
	[ItemID.MOLTEN_IRON]: { name: "Molten Iron", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.MOLTEN},
	[ItemID.MOLTEN_SILICON]: { name: "Molten Silicon", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.MOLTEN},
	[ItemID.MOLTEN_STEEL]: { name: "Molten Steel", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.MOLTEN},
	[ItemID.QUARTZ_CRUSHED]: { name: "Quartz Crushed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.RECYCLABLES]: { name: "Recyclables", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.RECYCLABLES_PRESSED]: { name: "Recyclables Pressed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.SALT]: { name: "Salt", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.SLAG_CRUSHED]: { name: "Slag Crushed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.URANIUM_ORE_CRUSHED]: { name: "Uranium Ore Crushed", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	[ItemID.WOODCHIPS]: { name: "Woodchips", category: ItemCategory.SEMI_PROCESSED_RESOURCE, state: ItemState.LOOSE},
	// #endregion

	// #region | Crafted Materials
	[ItemID.BRICKS]: { name: "Bricks", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.CONCRETE_SLAB]: { name: "Concrete Slab", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.CONSTRUCTION_PARTS]: { name: "Construction Parts", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.CONSTRUCTION_PARTS_II]: { name: "Construction Parts II", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.CONSTRUCTION_PARTS_III]: { name: "Construction Parts III", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.CONSTRUCTION_PARTS_IV]: { name: "Construction Parts IV", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.CONSUMER_ELECTRONICS]: { name: "Consumer Electronics", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.COPPER]: { name: "Copper", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.ELECTRONICS]: { name: "Electronics", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.ELECTRONICS_II]: { name: "Electronics II", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.ELECTRONICS_III]: { name: "Electronics III", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.FILTER_MEDIA]: { name: "Filter Media", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.LOOSE},
	[ItemID.FLOWERS]: { name: "Flowers", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.GLASS]: { name: "Glass", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.GOLD]: { name: "Gold", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.HOUSEHOLD_APPLIANCES]: { name: "Household Appliances", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.HOUSEHOLD_GOODS]: { name: "Household Goods", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.IRON]: { name: "Iron", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.LAB_EQUIPMENT]: { name: "Lab Equipment", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.LAB_EQUIPMENT_II]: { name: "Lab Equipment II", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.LAB_EQUIPMENT_III]: { name: "Lab Equipment III", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.LAB_EQUIPMENT_IV]: { name: "Lab Equipment IV", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MAINTENANCE_I]: { name: "Maintenance I", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.VIRTUAL},
	[ItemID.MAINTENANCE_II]: { name: "Maintenance II", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.VIRTUAL},
	[ItemID.MAINTENANCE_III]: { name: "Maintenance III", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.VIRTUAL},
	[ItemID.MECHANICAL_PARTS]: { name: "Mechanical Parts", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS]: { name: "Microchips", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_1_A]: { name: "Microchips Stage 1 A", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_1_B]: { name: "Microchips Stage 1 B", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_1_C]: { name: "Microchips Stage 1 C", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_2_A]: { name: "Microchips Stage 2 A", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_2_B]: { name: "Microchips Stage 2 B", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_2_C]: { name: "Microchips Stage 2 C", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_3_A]: { name: "Microchips Stage 3 A", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_3_B]: { name: "Microchips Stage 3 B", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_3_C]: { name: "Microchips Stage 3 C", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_4_A]: { name: "Microchips Stage 4 A", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.MICROCHIPS_STAGE_4_B]: { name: "Microchips Stage 4 B", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.PAPER]: { name: "Paper", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.PCB]: { name: "PCB", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.SERVER]: { name: "Server", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.SILICON_POLY]: { name: "Silicon (Poly)", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.SILICON_WAFER]: { name: "Silicon Wafer", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.SOLAR_CELL]: { name: "Solar Cell", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.SOLAR_CELL_MONO]: { name: "Solar Cell Mono", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.LOOSE},
	[ItemID.STEEL]: { name: "Steel", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.VEHICLE_PARTS]: { name: "Vehicle Parts", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.VEHICLE_PARTS_II]: { name: "Vehicle Parts II", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	[ItemID.VEHICLE_PARTS_III]: { name: "Vehicle Parts III", category: ItemCategory.CRAFTED_MATERIAL, state: ItemState.UNIT},
	// #endregion

	// #region | Foods and Medicals
	[ItemID.ANESTHETICS]: { name: "Anesthetics", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.ANIMAL_FEED]: { name: "Animal Feed", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.ANTIBIOTICS]: { name: "Antibiotics", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.BREAD]: { name: "Bread", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.CAKE]: { name: "Cake", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.CANOLA]: { name: "Canola", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.CHICKEN_CARCASS]: { name: "Chicken Carcass", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.COMPOST]: { name: "Compost", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.COOKING_OIL]: { name: "Cooking Oil", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.CORN_MASH]: { name: "Corn Mash", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.CORN]: { name: "Corn", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.DISINFECTANT]: { name: "Disinfectant", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.EGGS]: { name: "Eggs", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.ETHANOL]: { name: "Ethanol", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.FERTILITY]: { name: "Fertility", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.FERTILIZER_ORGANIC]: { name: "Fertilizer (Organic)", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.FERTILIZER_I]: { name: "Fertilizer I", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.FERTILIZER_II]: { name: "Fertilizer II", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.FLUID},
	[ItemID.FLOUR]: { name: "Flour", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.FOOD_PACK]: { name: "Food Pack", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.FRUIT]: { name: "Fruit", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.GREEN_MANURE]: { name: "Green Manure", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.VIRTUAL},
	[ItemID.MEAT_TRIMMINGS]: { name: "Meat Trimmings", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.MEAT]: { name: "Meat", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.MEDICAL_EQUIPMENT]: { name: "Medical Equipment", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.MEDICAL_SUPPLIES]: { name: "Medical Supplies", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.MEDICAL_SUPPLIES_II]: { name: "Medical Supplies II", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.MEDICAL_SUPPLIES_III]: { name: "Medical Supplies III", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.MORPHINE]: { name: "Morphine", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.POPPY]: { name: "Poppy", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.POTATO]: { name: "Potato", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.SAUSAGE]: { name: "Sausage", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.SNACK]: { name: "Snack", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.SOYBEAN]: { name: "Soybean", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.SUGAR_CANE]: { name: "Sugar Cane", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.SUGAR]: { name: "Sugar", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	[ItemID.TOFU]: { name: "Tofu", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.TREE_SAPLING]: { name: "Tree Sapling", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.VEGETABLES]: { name: "Vegetables", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.UNIT},
	[ItemID.WHEAT]: { name: "Wheat", category: ItemCategory.FOOD_AND_MEDICAL, state: ItemState.LOOSE},
	// #endregion

	// #region | Petrochemicals
	[ItemID.CRUDE_OIL]: { name: "Crude Oil", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.SOUR_WATER]: { name: "Sour Water", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.HEAVY_OIL]: { name: "Heavy Oil", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.MEDIUM_OIL]: { name: "Medium Oil", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.DIESEL]: { name: "Diesel", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.LIGHT_OIL]: { name: "Light Oil", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.FUEL_GAS]: { name: "Fuel Gas", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.NAPHTHA]: { name: "Naphtha", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.AMMONIA]: { name: "Ammonia", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.CHLORINE]: { name: "Chlorine", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.HYDROGEN]: { name: "Hydrogen", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.NITROGEN]: { name: "Nitrogen", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.OXYGEN]: { name: "Oxygen", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.HYDROGEN_FLUORIDE]: { name: "Hydrogen Fluoride", category: ItemCategory.PETROCHEMICAL, state: ItemState.FLUID},
	[ItemID.PLASTIC]: { name: "Plastic", category: ItemCategory.PETROCHEMICAL, state: ItemState.UNIT},
	[ItemID.RUBBER]: { name: "Rubber", category: ItemCategory.PETROCHEMICAL, state: ItemState.UNIT},
	// #endregion

	// #region | Power and Nuclears
	[ItemID.ELECTRICITY]: { name: "Electricity", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.VIRTUAL},
	[ItemID.MECHANICAL_POWER]: { name: "Mechanical Power", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.MECHANICAL},
	[ItemID.HEAT]: { name: "Heat", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.VIRTUAL},
	[ItemID.STEAM_SUPER]: { name: "Steam (Super)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.STEAM_HIGH]: { name: "Steam (High)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.STEAM_LOW]: { name: "Steam (Low)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.STEAM_DEPLETED]: { name: "Steam Depleted", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.BLANKET_FUEL]: { name: "Blanket Fuel", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.BLANKET_FUEL_ENRICHED]: { name: "Blanket Fuel (Enriched)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.CORE_FUEL]: { name: "Core Fuel", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.CORE_FUEL_SPENT]: { name: "Core Fuel (Spent)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.FLUID},
	[ItemID.DEPLETED_URANIUM]: { name: "Depleted Uranium", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.LOOSE},
	[ItemID.ENRICHED_URANIUM_4]: { name: "Enriched Uranium (4%)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.ENRICHED_URANIUM_20]: { name: "Enriched Uranium (20%)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.FISSION_PRODUCT]: { name: "Fission Product", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.MOX_ROD]: { name: "MOX Rod", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.PLUTONIUM]: { name: "Plutonium", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.REPROCESSED_URANIUM_1]: { name: "Reprocessed Uranium (1%)", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.RETIRED_WASTE]: { name: "Retired Waste", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.SPENT_FUEL]: { name: "Spent Fuel", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.SPENT_MOX]: { name: "Spent MOX", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.URANIUM_ROD]: { name: "Uranium Rod", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.UNIT},
	[ItemID.YELLOW_CAKE]: { name: "Yellow Cake", category: ItemCategory.POWER_AND_NUCLEAR, state: ItemState.LOOSE},
	// #endregion

	// #region | Wastes and Pollution
	[ItemID.AIR_POLLUTION]: { name: "Air Pollution", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.VIRTUAL},
	[ItemID.BIOMASS]: { name: "Biomass", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.LOOSE},
	[ItemID.CARBON_DIOXIDE]: { name: "Carbon Dioxide", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.FLUID},
	[ItemID.EXHAUST]: { name: "Exhaust", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.FLUID},
	[ItemID.RADIATION]: { name: "Radiation", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.VIRTUAL},
	[ItemID.SLAG]: { name: "Slag", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.LOOSE},
	[ItemID.SLUDGE]: { name: "Sludge", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.LOOSE},
	[ItemID.TOXIC_SLURRY]: { name: "Toxic Slurry", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.FLUID},
	[ItemID.WASTE]: { name: "Waste", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.LOOSE},
	[ItemID.WATER_POLLUTION]: { name: "Water Pollution", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.VIRTUAL},
	[ItemID.WASTE_PRESSED]: { name: "Waste Pressed", category: ItemCategory.WASTE_AND_POLLUTION, state: ItemState.LOOSE},
	[ItemID.WASTE_WATER]: { name: "Waste Water", category:ItemCategory.WASTE_AND_POLLUTION, state: ItemState.FLUID},
	// #endregion
};

// Individual item
export class Item {
	public readonly name: string;
	private readonly category: ItemCategory;
	private readonly state: ItemState;

	constructor({
		name,
		category,
		state
	}: ItemData) {
		this.name = name;
		this.category = category;
		this.state = state;
	}
}

// Instantiate all items
export const items: Record<ItemID, Item> = Object.fromEntries(

	// Filter enum for numerical IDs only
	Object.values(ItemID)
		.filter(value => typeof value === "number")
		.map(item_id => [
			item_id,
			new Item(item_data[item_id])
		])
) as Record<ItemID, Item>;
